### ISSUE TITLE
Keep `typeof` when getting types of a class' properties

### ISSUE THREAD

**Issue by alloy** [microsoft/flow2dts#15]
See this failing test case https://github.com/microsoft/flow2dts/commit/db58ceb278fb9b354ea5136e2d78b586e1640239

**Comment by ZihanChen-MSFT** [comment]
This bug tries to address the issue at
https://github.com/microsoft/flow2dts/blob/main/workbench/react-native/v0.63.3/outputs/ios/Libraries/Lists/VirtualizedSectionList.d.ts#L103

in `workbench\react-native\v0.63.3\hint\hint.json` there is
```json
        "/Libraries/Lists/VirtualizedSectionList.js.flow": {
...
                "defaultProps": [
                    {
                        "row": 116,
                        "column": 29,
                        "type": "type",
                        "resolvedDecl": {
                            "row": 273,
                            "column": 6,
                            "local": "DefaultProps",
                            "type": "type"
                        }
                    }
                ],
```

It comes from `workbench\react-native\v0.63.3\hint\Libraries\Lists\VirtualizedSectionList.hint.json`
```json
        {
            "source": {
                "row": 116,
                "column": 29,
                "local": "defaultProps"
            },
            "resolved": {
                "begin": {
                    "row": 273,
                    "column": 21
                },
                "end": {
                    "row": 283,
                    "column": 2
                },
                "libraryFolder": -1,
                "file": "/Libraries/Lists/VirtualizedList.js.flow"
            }
        },
```

The `resolved` object comes directly from calling `flow get-def`
While in `workbench\react-native\v0.63.3\inputs\Libraries\Lists\VirtualizedList.js.flow` we can see in line 273 it is:
```typescript
type DefaultProps = {|
  disableVirtualization: boolean,
  horizontal: boolean,
  initialNumToRender: number,
  keyExtractor: (item: Item, index: number) => string,
  maxToRenderPerBatch: number,
  onEndReachedThreshold: number,
  scrollEventThrottle: number,
  updateCellsBatchingPeriod: number,
  windowSize: number,
|};
```
but `defaultProps` must be in line 375:
```typescript
static defaultProps: DefaultProps,
```

This causes the hint file to mark `defaultProps` as `type` instead of `value`.

Need to try the command in cli directly, if it actually reports wrong result, then the only way to fix it immediately is to add an override.

**Comment by ZihanChen-MSFT** [comment]
Note that `hintFile.typeofs["X"][0].resolvedDecl.local` doesn't have to be `X` because import and export could do renaming.

**Comment by alloy** [comment]
```
$ yarn flow get-def workbench/react-native/v0.63.3/inputs/Libraries/Lists/VirtualizedSectionList.js.flow 116 29
/Users/eloy/Code/ReactNative/flow2dts/workbench/react-native/v0.63.3/inputs/Libraries/Lists/VirtualizedList.js.flow:273:21,283:2
```

This answer is correct, because on the requested [this line](https://github.com/microsoft/flow2dts/blob/7557beb31105acba9a59bf547cc9c48a840d7e25/workbench/react-native/v0.63.3/inputs/Libraries/Lists/VirtualizedSectionList.js.flow#L116)/column `typeof VirtualizedList.defaultProps` is referring to the _type_ of `VirtualizedList.defaultProps` and the _type_ is indeed defined [at line 273](https://github.com/microsoft/flow2dts/blob/7557beb31105acba9a59bf547cc9c48a840d7e25/workbench/react-native/v0.63.3/inputs/Libraries/Lists/VirtualizedList.js.flow#L273-L283).

Now if you add to e.g. line 114 a reference to the _value_ `VirtualizedList.defaultProps` and then ask flow for the definition you get the _value_ that [you were referring to](https://github.com/microsoft/flow2dts/blob/7557beb31105acba9a59bf547cc9c48a840d7e25/workbench/react-native/v0.63.3/inputs/Libraries/Lists/VirtualizedList.js.flow#L375).

```
$ yarn flow get-def workbench/react-native/v0.63.3/inputs/Libraries/Lists/VirtualizedSectionList.js.flow 114 17
/Users/eloy/Code/ReactNative/flow2dts/workbench/react-native/v0.63.3/inputs/Libraries/Lists/VirtualizedList.js.flow:375:10,375:21
```

**Comment by alloy** [comment]
Need to revert this workaround once this is fixed: https://github.com/microsoft/flow2dts/commit/8dca9d841f51d0aea270905541d007ef67017a3b

**Comment by ZihanChen-MSFT** [comment]
Today `flow2hint` copies everything from `workbench/react-native/VERSION/inputs` to `workbench/react-native/VERSION/hints/__modified__/` with all `typeof` removed except for `import typeof`.

When a type is needed and there is `typeof XXX`, by running `flow get-def` on a modified version which is `       XXX`, it reports:
```json
"Could not get definition for /Libraries/Lists/VirtualizedSectionList.js.flow:116:28\r\nNo possible types\r\n"
```

I could take this error as "this is not a type", which means "this is a value", to skip the next step which matches the result with declaration position list to determine what it actually is. Since the hint file only need to know "this is a value/type/class".

**Comment by alloy** [comment]
Related, but kinda the inverse; [here](https://github.com/microsoft/flow2dts/blob/36cbc9ebe6462820fed1ea70cdf74299d78d0e85/workbench/react-native/v0.63.3/inputs/Libraries/Linking/Linking.js.flow#L73) an _instance_ of `Linking` is being exported, but we convert it to if [a class was being exported](https://github.com/microsoft/flow2dts/blob/36cbc9ebe6462820fed1ea70cdf74299d78d0e85/workbench/react-native/v0.63.3/outputs/ios/Libraries/Linking/Linking.d.ts#L61).

**Comment by ZihanChen-MSFT** [comment]
Need to revert override once this is fixed: https://github.com/microsoft/flow2dts/commit/2e43b4043b5ef44936b461ea98edab89d61e10fa
